name: drupal8
recipe: drupal8
config:
  webroot: web
env_file:
  - .lando.env
services:
  appserver:
    build:
      - echo "Composer install ..." && composer install -q
tooling:
  drush:
    service: appserver
    cmd: drush
  drupal:
    service: appserver
    cmd: drupal --root=/app/web
  install:
    service: appserver
    cmd: ./scripts/install.sh
  update:
    service: appserver
    cmd: ./scripts/update.sh
