name: drupal9
recipe: drupal8
config:
  php: '7.4'
  webroot: web
env_file:
  - .lando.env
services:
  appserver:
    build:
      - echo "Composer install ..." && composer install -q
  database:
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
tooling:
  drush:
    service: appserver
    cmd: drush
  install:
    service: appserver
    cmd: ./scripts/install.sh
  update:
    service: appserver
    cmd: ./scripts/update.sh
